function Hd = FIR_Window(input,FC1,FC2)
%FIR_WINDOW Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the Signal Processing Toolbox 7.4.
% Generated on: 21-Dec-2018 12:03:35

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = input;  % Sampling Frequency

N    = 20;       % Order
Fc1  = FC1;     % First Cutoff Frequency
Fc2  = FC2;    % Second Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = rectwin(N+1);

% Calculate the coefficients using the FIR1 function.
if Fc1 == 0 
    b  = fir1(N, Fc2/(Fs/2), 'low', win, flag);
else
    b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
end
Hd = dfilt.dffir(b);
% [EOF]
